# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- folder-deployment

variables:
  azureSubscription: 'Azure subscription 1(7885d7ba-c47d-4eb7-a5f7-9fdd6158f238)'
  appName: 'az-pipeline-deployment'
  slotName: 'production'

stages:
- stage: Build
  displayName: Build Stage
  jobs: 
  - job: Build
    displayName: Build Job
    pool:
      name: Default
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'npm install'
    - task: ArchiveFiles@2
      displayName: 'Archive Files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
        
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(slotName)
    pool:
      name: Default
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy $(appName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webApp'
              appName: $(appName)
              # deployToSlotOrASE: true
              resourceGroupName: 'az-database'
 #             slotName: 'production'
              package: $(Pipeline.Workspace)/Production/$(Build.BuildId).zip
              deploymentMethod: 'auto'
              startUpCommand: 'npm run start'